name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TF_VERSION: 1.12.0
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug AWS Configuration
        run: |
          echo "AWS Region: $AWS_REGION"
          aws configure list
          aws sts get-caller-identity

      - name: Normalize Terraform env var casing
        run: |
          echo "TF_VAR_account_id=${{ secrets.TF_VAR_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_db_password=${{ secrets.TF_VAR_DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Clean previous .terraform dir (optional but safe)
        run: rm -rf .terraform

      - name: Debug Terraform input variables (safe)
        run: |
          echo "Terraform Environment Debug"
          echo "TF_VAR_account_id=${TF_VAR_account_id}"
          echo "TF_VAR_db_password=[REDACTED]"
          echo "All TF_VAR_* seen by environment:"
          env | grep TF_VAR || echo "No TF_VARs found!"

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply (Main Only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false -auto-approve tfplan
